bcc-code/bcc-vote

client/src/components/MeetingTile.vue
client/src/components/QuestionData.vue
client/src/views/AdministerVoting.vue
client/src/views/Home.vue
client/src/views/Vote.vue
server/src/authentication.ts
server/src/channels.ts
server/src/services/answers/answers.hooks.ts
server/src/services/meetings/meetings.hooks.ts
server/src/services/members/members.class.ts
server/src/services/users/users.hooks.ts

Those are some improvements and butfixes I've done earlier maybe it is worth to merge.

Improvements

---

client/src/components/form-field.vue

Fixed explicit form field values

Fixed explicit form field values - Hotfix master

---

client/src/components/polling-event-card.vue
client/src/domain/PollingEvent.ts
client/src/localization/master.json
client/src/router/routes.ts
client/src/views/AdminEventLive.vue
client/src/views/AdminEventPrepare.vue
client/src/views/Home.vue

UI side for linking to a Polling event

Added Homepage cards

---

client/src/domain/PollingEvent.ts
client/src/views/AdminEventLive.vue
client/src/views/AdminEventPrepare.vue
client/src/views/PollingEventCreate.vue

Replaced string creatorID to number

Replaced string creatorID to number

---

client/src/assets/style.css
client/src/components/poll-popover.vue
client/src/main.ts
client/src/views/AdminEventLive.vue
client/src/views/ParticipantLobby.vue

Answer page finished design

---

client/src/components/poll-results.vue

Results progress bar fix

---

server/src/services/answer/answer.hooks.ts
server/src/services/authentication/authentication-helpers.ts
server/src/services/authentication/authentication.ts

https://github.com/bcc-code/bcc-vote/issues/119

Get roles from related property from members

---

client/src/App.vue
client/src/components/layout-footer.vue
client/src/views/Home.vue

style bugfix for recent release

Homepage padding fix

---

client/src/App.vue

Layout fix for pages

---

client/src/components/poll-form.vue
client/src/localization/master.json

Removed option placeholder

---

server/src/domain/User.ts

'OrgRepresentative' and 'VotingAdmin'

Added latest roleNames

---

client/src/components/polling-event-form.vue
client/src/main.ts
client/src/router/index.ts
server/src/domain/User.ts
server/src/permissions/appAbility.ts
server/src/services/authentication/authentication-helpers.ts
server/src/services/authentication/authentication.ts
server/test/app-ability-tests.ts
server/test/setup-tests/test-set.ts

Polling admin permissions

---

client/src/components/copy-text.vue
client/src/components/poll-form.vue
client/src/components/polling-event-card.vue
client/src/components/polling-event-form.vue
client/src/components/tooltip.vue
client/src/localization/master.json

Changed texts, added tooltip component

---

client/src/App.vue
client/src/components/layout-header.vue
client/src/router/index.ts
client/src/router/routes.ts
client/src/views/Error.vue

Error page fixed

---

server/src/db-migrations/001_initial_collections.ts
server/src/db-migrations/002_polling_even_and_poll_indexes.ts

https://github.com/bcc-code/bcc-vote/issues/205

Indexes for polling even and poll collections

---

server/src/services/polling-event/polling-event.hooks.ts

Closes bug about not triggering the Thank you page.

Added lastchanged to Polling Event hooks

---

client/src/components/admin-polling-event-panel.vue
client/src/components/event-filter-info.vue
client/src/components/form-field.vue
client/src/components/polling-event-card.vue
client/src/components/polling-event-form.vue
client/src/domain/PollingEvent.ts
client/src/localization/no_vote_master.json
client/src/localization/vote_master.json

Polling event details

---

client/src/components/poll-results.vue
client/src/store/result.ts
client/src/views/LiveResults.vue
server/src/services/answer/answer.class.ts
server/src/services/answer/answer.hooks.ts

Back to arango db

---

client/src/components/admin-polling-event-panel.vue
client/src/components/saved-poll.vue
client/src/localization/no_vote_master.json
client/src/localization/vote_master.json

Closing question confirmation

---

client/src/components/admin-polling-event-panel.vue
client/src/components/poll-results.vue
client/src/components/saved-poll.vue
client/src/localization/de_vote_master.json
client/src/localization/en_vote_master.json
client/src/localization/es_vote_master.json
client/src/localization/fi_vote_master.json
client/src/localization/fr_vote_master.json
client/src/localization/nl_vote_master.json
client/src/localization/no_vote_master.json
client/src/localization/ro_vote_master.json
client/src/localization/vote_master.json
client/src/store/result.ts
client/src/views/LiveResults.vue
server/src/services/answer/answer.class.ts
server/src/services/answer/answer.hooks.ts

Added translations that Amelie changed

Translations added

---

server/src/services/answer/answer.hooks.ts
server/test/answer-tests.ts

fix to the double vote issue

---

client/package-lock.json
server/package-lock.json
server/package.json

*removed nedb, unused dependency
*performed npm audit on both client and server, some manual

removed nedb

---

client/src/components/admin-polling-event-panel.vue
client/src/components/confirm-popover.vue
client/src/components/poll-popover.vue
client/src/components/polling-event-card.vue
client/src/components/saved-poll.vue
client/src/views/Lobby.vue
client/src/views/ThankYou.vue

Design feedback response

---

server/package-lock.json
server/package.json
server/src/app.hooks.ts
server/src/db-migrations/001_initial_collections.ts
server/src/db-migrations/002_polling_even_and_poll_indexes.ts
server/src/index.ts
server/src/logger.ts
server/src/services/answer/answer.hooks.ts
server/src/services/authentication/authentication.ts
server/src/services/members-external/members-external-services.ts
server/src/services/poll-result/poll-result.class.ts
server/src/services/polling-event/polling-event.hooks.ts
server/test/answer-tests.ts
server/test/app-ability-tests.ts
server/test/channels-tests.ts

Closes #252 
Error logs and normal info logs are now showing up in a specific log. 
Dev logs: https://cloudlogging.app.goo.gl/ozsycgTPMXqzcRfj7

Error severity added

---

client/package-lock.json
client/package.json
client/src/main.ts
client/src/router/index.ts
client/src/router/routes.ts
client/src/shims-vue.d.ts
client/src/views/Home.vue

closes #263 
Basic google analytics

Add google analytics

---

client/package-lock.json
client/package.json
client/src/components/admin-polling-event-panel.vue
client/src/components/admin-polls-panel.vue
client/src/components/admin-results-panel.vue
client/src/components/copy-text.vue
client/src/components/poll-form.vue
client/src/components/poll-popover.vue
client/src/components/poll-results.vue
client/src/components/polling-event-form.vue
client/src/components/saved-poll.vue
client/src/functions/helpers.ts
client/src/main.ts
client/src/router/index.ts
client/src/shims-vue.d.ts
client/src/views/AdminEvent.vue
client/src/views/AdminPollResult.vue
client/src/views/LiveResults.vue
client/src/views/Lobby.vue
server/src/services/poll/poll.hooks.ts
server/src/services/polling-event/polling-event.hooks.ts

closes #264 
It works surprisingly well because it will automatically send all the unhandled errors

Add sentry io

---

client/src/components/layout-header.vue
client/src/components/polling-event-card.vue
client/src/router/index.ts

Homepage buttons improvment

---

server/src/services/authentication/authentication-helpers.ts

Personrole prepare org Id change

---

client/src/components/layout-header.vue
client/src/components/polling-event-card.vue
client/src/main.ts
client/src/router/index.ts
client/src/router/routes.ts
client/src/shims-vue.d.ts

Navigation error fix

---

client/src/components/input-textarea-field.vue
client/src/components/poll-results.vue
client/src/components/poll-vote.vue
client/src/router/routes.ts
client/src/views/ThankYou.vue

closes #285 
it's supposed to fix those:
https://sentry.io/organizations/bcc-hj/issues/2483484218/?project=5831770&query=is%3Aunresolved
https://sentry.io/organizations/bcc-hj/issues/2483368059/?project=5831770&query=is%3Aunresolved

Type errors - part 1

---

server/src/services/members-external/members-external-services.ts

Timeout on find event fix

---

server/.gitignore
server/src/services/authentication/authentication.ts
server/src/utils/promiseWithTimeout.ts

Closes #311 
- Adds timeout for request to Members that seems to be the root cause for this issue
- Improves logging

Create authentication Timeout precaution

---

server/package-lock.json
server/package.json
server/src/logger.ts
server/src/services/authentication/authentication.ts

This PR:
- improves logging setup 
- improves logging auth errors logging
- bump socket-io to the same version as in members

Hotfix/bad connection to members--logging

---

server/src/db-migrations/001_initial_collections.ts
server/src/db-migrations/002_polling_even_and_poll_indexes.ts
server/src/services/authentication/authentication.ts
server/src/utils/promiseWithTimeout.ts

This PR removes code that was throwing exception on trying to reach members API

Fix dropping connection to members

---

server/package-lock.json
server/package.json

This PR only updates our own packages (arangodb-migrations and feathers-arangodb adapter) and adds security updates

updates and security fixes

---

server/src/app.ts

imports env vars in app.ts so that the tests can use them

import env vars for tests to work

---

LICENSE.md

This PR adds AGPL v3 license, according to Reng suggestion

add AGPL v3 license

---

server/src/app.hooks.ts

closes #356
In #348 it was forgotten to sync updates from arangoDB to firestore,
Adds the syncing logic in app.hooks

sync updates to firestore

---

client/src/assets/style.css
client/src/components/confirm-popover.vue
client/src/components/poll-popover.vue
client/src/components/poll-vote.vue

closes #343
Deactivates vote button when the request is sent so the user cannot accidentally vote twice

Add debounce when voting

---

client/src/localization/de_vote_master.json
client/src/localization/en_vote_master.json
client/src/localization/es_vote_master.json
client/src/localization/fi_vote_master.json
client/src/localization/fr_vote_master.json
client/src/localization/nl_vote_master.json
client/src/localization/no_vote_master.json
client/src/localization/ro_vote_master.json
client/src/localization/vote_master.json
client/src/mixins.ts

This PR changes message shown to user when poll is not active, to better inform user of what he can do (refresh page)

Poll is not active

---

client/src/functions/appInsightsTelemetry.ts
client/src/functions/auth0.ts
client/src/main.ts
server/package-lock.json
server/package.json
server/src/permissions/appAbility.ts

Fix unhandled error, bump arango adapter version

Fix  auth0 undefined

---

client/src/main.ts
client/src/store/index.ts
client/src/views/Lobby.vue

Sentry errors fixes

---

client/src/views/Lobby.vue
docs/investigations/timeout.md
server/src/domain/User.ts
server/src/services/authentication/authentication-helpers.ts
server/src/services/authentication/authentication.ts
server/src/services/authentication/customAuthentication.ts
server/test/answer-tests.ts
server/test/authentication.ts

Closes [#1975](https://github.com/bcc-code/bcc-membership/issues/1975)

Timeout in Lobby bugfix

---

docs/postmortems/event-oslo-follo-june-2022.md

Add postmortem for issues during the Juni events

Add postmortem for issues during the Juni events

---

client/package-lock.json
client/package.json

Grouped dependancies from dependabot

Dependancies June 2022
